# Generated by Django 5.1.6 on 2025-02-20 02:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chainsaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('penro', models.CharField(max_length=100)),
                ('cenro', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('CUTTING IN PRIVATE PLANTATION FOR COMMERCIAL USE', 'CUTTING IN PRIVATE PLANTATION FOR COMMERCIAL USE'), ('CUTTING IN TENURE AREA FOR PERSONAL/NON COMMERCIAL USE', 'CUTTING IN TENURE AREA FOR PERSONAL/NON COMMERCIAL USE')], max_length=100)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('cert_reg_number', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('registration_status', models.CharField(choices=[('RENEWED', 'RENEWED'), ('FOR RENEWAL', 'FOR RENEWAL'), ('EXPIRED', 'EXPIRED')], max_length=50)),
                ('date_renewal', models.DateField(blank=True, null=True)),
                ('horse_power', models.CharField(max_length=50)),
                ('guidebar_length', models.CharField(max_length=50)),
                ('denr_sticker', models.CharField(max_length=100)),
                ('ctpo_number', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='chainsaw_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('integrated', models.CharField(blank=True, choices=[('APPLICABLE', 'Applicable'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20, null=True)),
                ('wpp_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.CharField(blank=True, max_length=200, null=True)),
                ('plant', models.CharField(blank=True, max_length=200, null=True)),
                ('drc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('local_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('imported_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('supplier_info', models.CharField(blank=True, max_length=500, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('wood_status', models.CharField(blank=True, choices=[('ACTIVE_NEW', 'Active/New'), ('ACTIVE_RENEWAL', 'Active/Renewed'), ('EXISTING', 'Existing'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE_NEW', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('TCP', 'TCP'), ('STCP', 'STCP'), ('PLTP', 'PLTP'), ('SPLTP', 'SPLTP')], default='TCP', max_length=5)),
                ('permit_number', models.CharField(help_text='Permit identification number', max_length=20)),
                ('permittee', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('total_volume_granted', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Volume Granted (cu.m.)')),
                ('gross_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Volume (cu.m.)')),
                ('net_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Volume (cu.m.)')),
                ('permit_issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('rep_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('permit_type', 'permit_number')},
            },
        ),
        migrations.CreateModel(
            name='CuttingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('species', models.CharField(max_length=100)),
                ('no_of_trees', models.IntegerField(default=0)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_remaining_balance', models.DecimalField(db_column='remaining_balance', decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('parent_tcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cutting')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Lumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('trade_name', models.CharField(max_length=200)),
                ('manager_owner', models.CharField(max_length=200)),
                ('permit_no', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField()),
                ('volume_cubic_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('species', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
