# Generated by Django 5.0.4 on 2025-02-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainsaw',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
