# Generated by Django 5.1.6 on 2025-02-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area (ha.)'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='lot_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot No.'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='no_of_trees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Trees'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='permit_file',
            field=models.FileField(blank=True, null=True, upload_to='permits/', verbose_name='Permit File'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='tax_dec_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Declaration No.'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='tct_oct_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TCT/OCT No.'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='rep_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Representative'),
        ),
    ]
