# Generated by Django 5.0.4 on 2025-02-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_chainsaw_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainsaw',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Brand'),
        ),
    ]
