# Generated by Django 5.0.4 on 2025-02-12 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_chainsaw_date_acquired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='species_name',
        ),
        migrations.AddField(
            model_name='cutting',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cutting',
            name='gross_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cutting',
            name='lot_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cutting',
            name='rep_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cutting',
            name='species',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cutting',
            name='tax_dec_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cutting',
            name='tct_oct_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cutting',
            name='total_volume_granted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='no_of_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='permit_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='permittee',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='tcp_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CuttingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('species', models.CharField(max_length=100)),
                ('no_of_trees', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('parent_tcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_records', to='base.cutting')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
