# Generated by Django 5.1.6 on 2025-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cutting_area_cutting_lot_no_cutting_no_of_trees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingrecord',
            name='number_of_trees',
            field=models.IntegerField(default=0),
        ),
    ]
