# Generated by Django 5.0.4 on 2025-02-12 03:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_cutting_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingrecord',
            name='_remaining_balance',
            field=models.DecimalField(db_column='remaining_balance', decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuttingrecord',
            name='parent_tcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cutting'),
        ),
    ]
