# Generated by Django 5.1.6 on 2025-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cutting_latitude_cutting_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinates (e.g. 10.123456)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinates (e.g. 123.456789)', max_digits=9, null=True)),
            ],
        ),
    ]
