# Generated by Django 5.0.4 on 2025-02-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cuttingrecord__remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cutting',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='permittee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='rep_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='tcp_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='total_volume_granted',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
