# Generated by Django 5.0.4 on 2025-02-07 15:05

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_chainsaw_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainsaw',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=base.models.Chainsaw.get_file_path, verbose_name='Upload File'),
        ),
    ]
