# Generated by Django 5.1.6 on 2025-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cuttingpermit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
