# Generated by Django 5.1.6 on 2025-03-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_lumber_volume_cubic_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumber',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
