# Generated by Django 5.0.4 on 2025-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_cutting_options_cutting_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='no_of_trees',
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='tax_dec_no',
        ),
        migrations.AddField(
            model_name='cutting',
            name='net_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Volume (cu.m.)'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='number_of_trees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Trees'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='tax_declaration_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Declaration No.'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area (ha.)'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='gross_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Volume (cu.m.)'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='lot_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot No.'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='tct_oct_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TCT/OCT No.'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='total_volume_granted',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Volume Granted (cu.m.)'),
        ),
    ]
