# Generated by Django 5.1.6 on 2025-02-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cutting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='status',
        ),
        migrations.AddField(
            model_name='cutting',
            name='situation',
            field=models.CharField(choices=[('Good', 'Good'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
