# Generated by Django 5.0.4 on 2025-02-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_cutting_no_of_trees_remove_cutting_tax_dec_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutting',
            old_name='tax_declaration_no',
            new_name='tax_dec_no',
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='number_of_trees',
        ),
        migrations.AddField(
            model_name='cutting',
            name='no_of_trees',
            field=models.IntegerField(default=0, verbose_name='Number of Trees'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='tcp_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='TCP No.'),
        ),
    ]
