# Generated by Django 5.0.4 on 2025-02-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_wood_options_wood_created_at_wood_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='_days_remaining',
            field=models.IntegerField(db_column='days_remaining', default=0),
        ),
    ]
