# Generated by Django 5.1.6 on 2025-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_cutting_status_cutting_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='situation',
            field=models.CharField(choices=[('Good', 'Good'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
