# Generated by Django 5.1.6 on 2025-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_lumber_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodProcessingPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('permit_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon')], default='active', max_length=20)),
            ],
        ),
    ]
