# Generated by Django 5.0.4 on 2025-02-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cutting__days_remaining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wood',
            options={},
        ),
        migrations.RemoveField(
            model_name='wood',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wood',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wood',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wood',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wood',
            name='alr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='business',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='dpc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='imported_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='integrated',
            field=models.CharField(blank=True, choices=[('APPLICABLE', 'Applicable'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='local_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='plant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='supplier_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='wpp_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
