# Generated by Django 5.0.4 on 2025-02-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_wood_options_remove_wood_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wood',
            name='dpc',
        ),
        migrations.AddField(
            model_name='wood',
            name='approved_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='wood',
            name='drc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DRC (cu.m)'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='alr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ALR (m³)'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='imported_volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Imported Volume'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='local_volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Local Volume'),
        ),
    ]
