# Generated by Django 5.1.6 on 2025-02-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_cutting_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='permit_file',
            field=models.FileField(blank=True, help_text='Upload permit document', null=True, upload_to='permits/'),
        ),
    ]
