# Generated by Django 5.1.6 on 2025-02-22 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_cutting_permit_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='gross_volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='net_volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
    ]
