# Generated by Django 5.1.6 on 2025-03-13 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_chainsaw_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='date_issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wood',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
