# Generated by Django 5.0.4 on 2025-02-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_wood_dpc_wood_approved_by_wood_drc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wood',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area'),
        ),
    ]
