# Generated by Django 5.1.6 on 2025-03-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_wood_date_issued_alter_wood_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='imported_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Enter latitude (e.g., 10.123456)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Enter longitude (e.g., 123.305953)', max_digits=9, null=True),
        ),
    ]
