# Generated by Django 5.1.6 on 2025-02-22 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_cutting_gross_volume_alter_cutting_net_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='gross_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinates (e.g. 10.123456)', max_digits=9, null=True, validators=[django.core.validators.MaxValueValidator(999.999999)]),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinates (e.g. 123.456789)', max_digits=9, null=True, validators=[django.core.validators.MaxValueValidator(999.999999)]),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='net_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
    ]
