# Generated by Django 5.0.4 on 2025-02-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_wood_options_alter_wood_alr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wood',
            options={},
        ),
    ]
