# Generated by Django 5.1.6 on 2025-02-22 02:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_cutting_gross_volume_alter_cutting_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutting',
            options={'ordering': ['-date_issued']},
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='permit_issue_date',
        ),
        migrations.AddField(
            model_name='cutting',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cutting',
            name='gross_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='net_volume',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
