# Generated by Django 5.1.5 on 2025-02-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_wood_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wood',
            name='wood_status',
            field=models.CharField(blank=True, choices=[('ACTIVE_NEW', 'Active/New'), ('ACTIVE_RENEWAL', 'Active/Renewal'), ('EXISTING', 'Existing'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE_NEW', max_length=20, null=True),
        ),
    ]
