# Generated by Django 5.1.6 on 2025-02-24 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_cutting_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingrecord',
            name='_remaining_balance',
        ),
        migrations.RemoveField(
            model_name='cuttingrecord',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='cuttingrecord',
            name='no_of_trees',
        ),
        migrations.AddField(
            model_name='cuttingrecord',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuttingrecord',
            name='calculated_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuttingrecord',
            name='number_of_trees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cuttingrecord',
            name='parent_tcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_records', to='base.cutting'),
        ),
    ]
