# Generated by Django 5.1.6 on 2025-03-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_wood_alr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='latitude',
            field=models.CharField(blank=True, help_text='Enter latitude (e.g., 9.990572)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='longitude',
            field=models.CharField(blank=True, help_text='Enter longitude (e.g., 123.305953)', max_length=20, null=True),
        ),
    ]
