# Generated by Django 5.0.4 on 2025-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_wood_wood_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='wood_status',
            field=models.CharField(blank=True, choices=[('ACTIVE_NEW', 'Active/New'), ('ACTIVE_RENEWAL', 'Active/Renewed'), ('EXISTING', 'Existing'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE_NEW', max_length=20, null=True),
        ),
    ]
