# Generated by Django 5.1.6 on 2025-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_cuttingrecord_date_cuttingrecord_volume_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumber',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lumber_files/'),
        ),
    ]
