# Generated by Django 5.1.6 on 2025-03-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_wood_alr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wood',
            options={},
        ),
        migrations.RemoveField(
            model_name='wood',
            name='business',
        ),
        migrations.RemoveField(
            model_name='wood',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wood',
            name='integrated',
        ),
        migrations.RemoveField(
            model_name='wood',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='wood',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wood',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='business_name',
            field=models.CharField(blank=True, default='Default Business Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='alr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='approved_by',
            field=models.CharField(default='CENRO', max_length=255),
        ),
        migrations.AlterField(
            model_name='wood',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='wood_attachments/'),
        ),
        migrations.AlterField(
            model_name='wood',
            name='date_released',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wood',
            name='drc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wood',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='local_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wood',
            name='supplier_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(choices=[('Resawmill-new', 'RESAWMILL-NEW'), ('Resawmill-renew', 'RESAWMILL-RENEWAL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wood',
            name='wpp_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='wood',
            table='base_wood',
        ),
    ]
