# Generated by Django 5.1.6 on 2025-03-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_lumber_brgy_lumber_contact_number_lumber_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumber',
            name='brgy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='source_supplier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
