# Generated by Django 5.1.6 on 2025-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_cutting_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='situation',
            field=models.CharField(choices=[('Good', 'Good'), ('Pending', 'Pending'), ('Consumed', 'Consumed'), ('Active', 'Active')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Consumed'), ('PENDING', 'Pending'), ('Active', 'Active'), ('Expired', 'Expired'), ('Pending', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
