# Generated by Django 5.1.6 on 2025-03-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_cutting_situation_alter_cutting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingrecord',
            name='other_species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuttingrecord',
            name='species',
            field=models.CharField(choices=[('Molave', 'Molave'), ('Sawn Lumber', 'Sawn Lumber'), ('Fuel Wood', 'Fuel Wood'), ('Yemane', 'Yemane'), ('Mahogany', 'Mahogany'), ('Narra', 'Narra'), ('Minepoles', 'Minepoles'), ('Teabolts', 'Teabolts'), ('Others', 'Others')], default='Molave', max_length=100),
        ),
    ]
