# Generated by Django 5.1.6 on 2025-03-02 14:49

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_lumber_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wood',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='wood_files/'),
        ),
        migrations.AddField(
            model_name='wood',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='alr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Area in hectares', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wood',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wood',
            name='date_released',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wood',
            name='drc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wood',
            name='imported_volume',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Imported volume in cubic meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wood',
            name='integrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wood',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinates', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='local_volume',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Local volume in cubic meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wood',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinates', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='plant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='wood_status',
            field=models.CharField(choices=[('EXISTING', 'Existing'), ('EXPIRED', 'Expired/Renewed'), ('ACTIVE_NEW', 'Active/New')], default='ACTIVE_NEW', max_length=20),
        ),
    ]
