# Generated by Django 5.1.6 on 2025-03-02 14:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_wood_attachment_wood_created_at_wood_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wood',
            options={'ordering': ['-date_issued']},
        ),
        migrations.AlterField(
            model_name='wood',
            name='alr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ALR in cubic meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='wood',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Area in hectares', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='wood',
            name='drc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='DRC in cubic meters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='wood',
            name='imported_volume',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Imported volume in cubic meters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='wood',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='local_volume',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Local volume in cubic meters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='wood',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='plant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='supplier_info',
            field=models.CharField(blank=True, help_text='Location/Address of supplier', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(choices=[('Integrated', 'Integrated'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50),
        ),
    ]
