# Generated by Django 5.1.6 on 2025-03-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_cuttingrecord_other_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumerecord',
            name='other_species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='species',
            field=models.CharField(choices=[('Molave', 'Molave'), ('Yemane', 'Yemane'), ('Mahogany', 'Mahogany'), ('Narra', 'Narra'), ('Minepoles', 'Minepoles'), ('Others', 'Others')], max_length=100),
        ),
    ]
