# Generated by Django 5.1.6 on 2025-03-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_volumerecord_other_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='permit_type',
            field=models.CharField(choices=[('TCP', 'TCP'), ('PLTP', 'PLTP'), ('STCP', 'STCP'), ('SPLTP', 'SPLTP')], default='TCP', max_length=100),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='situation',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Consumed'), ('PENDING', 'Pending'), ('Active', 'Active'), ('Expired', 'Expired'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='species',
            field=models.CharField(choices=[('Sawn Lumber', 'Sawn Lumber'), ('Fuel Wood', 'Fuel Wood'), ('Minepoles', 'Minepoles'), ('Molave', 'Molave'), ('Yemane', 'Yemane'), ('Mahogany', 'Mahogany'), ('Narra', 'Narra'), ('Logbolts', 'Logbolts'), ('Others', 'Others')], max_length=100),
        ),
    ]
