# Generated by Django 5.1.6 on 2025-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_wood_options_alter_wood_alr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='integrated',
            field=models.CharField(choices=[('Applicable', 'Applicable'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
