# Generated by Django 5.1.6 on 2025-03-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_wood_integrated_alter_wood_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wood',
            options={'ordering': ['-date_issued'], 'verbose_name': 'Wood Processing Plant', 'verbose_name_plural': 'Wood Processing Plants'},
        ),
        migrations.AlterField(
            model_name='wood',
            name='business',
            field=models.CharField(default='', help_text='Business name', max_length=200),
        ),
        migrations.AlterField(
            model_name='wood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='integrated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='name',
            field=models.CharField(default='', help_text='Name of the wood processing plant', max_length=200),
        ),
        migrations.AlterField(
            model_name='wood',
            name='plant',
            field=models.CharField(default='', help_text='Plant location/address', max_length=200),
        ),
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(choices=[('SAWMILL', 'Sawmill'), ('MINI-SAWMILL', 'Mini-Sawmill'), ('RE-SAWMILL', 'Re-Sawmill'), ('VENEER PLANT', 'Veneer Plant'), ('PLYWOOD PLANT', 'Plywood Plant'), ('OTHER', 'Other')], default='SAWMILL', max_length=50),
        ),
        migrations.AlterField(
            model_name='wood',
            name='wood_status',
            field=models.CharField(choices=[('ACTIVE_NEW', 'Active (New)'), ('ACTIVE_RENEWED', 'Active (Renewed)'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE_NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='wood',
            name='wpp_number',
            field=models.CharField(default='', help_text='WPP registration number', max_length=100),
        ),
    ]
