# Generated by Django 5.1.6 on 2025-03-26 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_cutting_permit_type_alter_cutting_situation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cutting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_species', to='base.cutting')),
            ],
            options={
                'verbose_name_plural': 'Tree Species',
                'ordering': ['species'],
            },
        ),
    ]
