# Generated by Django 5.1.6 on 2025-03-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_wood_options_alter_wood_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(choices=[('RE-SAWMILL', 'Resawmill-new'), ('SAWMILL', 'Sawmill'), ('MINI-SAWMILL', 'Mini-Sawmill'), ('VENEER PLANT', 'Veneer Plant'), ('PLYWOOD PLANT', 'Plywood Plant'), ('OTHER', 'Other')], default='RE-SAWMILL', max_length=50),
        ),
    ]
