# Generated by Django 5.1.6 on 2025-03-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_wood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='type',
            field=models.CharField(choices=[('Resawmill-new', 'Resawmill-new'), ('Resawmill-renew', 'Resawmill-renew')], max_length=50),
        ),
    ]
