# Generated by Django 5.1.6 on 2025-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_cuttingpermit_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cutting_files/'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='other_species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
