# Generated by Django 5.1.6 on 2025-03-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_cutting_file_cutting_other_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='wood_status',
            field=models.CharField(choices=[('ACTIVE (NEW)', 'Active (New)'), ('ACTIVE (RENEWED)', 'Active (Renewed)'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
