# Generated by Django 5.1.6 on 2025-03-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_wood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='situation',
            field=models.CharField(choices=[('Good', 'Good'), ('Pending', 'Pending'), ('Active', 'Active'), ('Expired', 'Expired')], default='Pending', max_length=50, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='species',
            field=models.TextField(default='Molave', help_text='For PLTP, separate multiple species with commas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuttingrecord',
            name='species',
            field=models.CharField(choices=[('Molave', 'Molave'), ('Molave SL', 'Molave SL'), ('Molave Fuel Wood', 'Molave Fuel Wood'), ('Germelina', 'Germelina'), ('Germelina SL', 'Germelina SL'), ('Germelina Fuel Wood', 'Germelina Fuel Wood'), ('Mahogany', 'Mahogany'), ('Mahogany SL', 'Mahogany SL'), ('Mahogany Fuel Wood', 'Mahogany Fuel Wood'), ('Narra', 'Narra'), ('Narra SL', 'Narra SL'), ('Narra Fuel Wood', 'Narra Fuel Wood')], default='Molave', max_length=100),
        ),
    ]
