# Generated by Django 5.1.6 on 2025-03-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_wood_wood_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wood',
            name='wood_status',
            field=models.CharField(choices=[('ACTIVE_NEW', 'Active (New)'), ('ACTIVE_RENEWED', 'Active (Renewed)'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE_NEW', max_length=20),
        ),
    ]
