# Generated by Django 5.1.6 on 2025-04-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_cutting_location_alter_wood_wood_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='cutting',
            name='or_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cutting',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
