# Generated by Django 5.1.6 on 2025-04-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_cutting_contact_number_cutting_or_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treespecies',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
