# Generated by Django 5.1.6 on 2025-03-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingrecord',
            name='species',
            field=models.CharField(choices=[('Molave', 'Molave'), ('Sawn Lumber', 'Sawn Lumber'), ('Fuel Wood', 'Fuel Wood'), ('Yemane', 'Yemane'), ('Mahogany', 'Mahogany'), ('Narra', 'Narra'), ('Minepoles', 'Minepoles'), ('Teabolts', 'Teabolts')], default='Molave', max_length=100),
        ),
    ]
