# Generated by Django 5.1.6 on 2025-03-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cuttingrecord_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumber',
            options={'ordering': ['-date_issued']},
        ),
        migrations.RemoveField(
            model_name='lumber',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lumber',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lumber',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='lumber',
            name='brgy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='manager_owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='municipality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='source_supplier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='trade_name',
            field=models.CharField(max_length=100),
        ),
    ]
