# Generated by Django 5.1.6 on 2025-03-09 14:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_add_lumber_status_and_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumber',
            name='volume_cubic_meter',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
