# Generated by Django 5.1.6 on 2025-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_woodprocessingplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodprocessingplant',
            name='status',
            field=models.CharField(choices=[('ACTIVE_NEW', 'Active (New)'), ('ACTIVE_RENEWED', 'Active (Renewed)'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE_NEW', max_length=20),
        ),
    ]
