# Generated by Django 5.1.6 on 2025-03-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_woodprocessingplant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainsaw',
            name='registration_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RENEWED', 'RENEWED'), ('RENEWAL', 'RENEWAL'), ('EXPIRED', 'EXPIRED')], max_length=50),
        ),
    ]
