# Generated by Django 5.1.6 on 2025-03-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_wood_area_alter_wood_imported_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='alr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual Log Requirement (ALR)', max_digits=10, null=True),
        ),
    ]
