# Generated by Django 5.1.6 on 2025-03-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_wood_latitude_alter_wood_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wood',
            name='alr',
            field=models.CharField(blank=True, help_text='Annual Log Requirement (ALR)', max_length=20, null=True),
        ),
    ]
