# Generated by Django 5.1.6 on 2025-03-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_wood_options_remove_wood_business_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutting',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cutting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cutting',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Consumed'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='date_issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='gross_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='lot_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='net_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='no_of_trees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='permit_file',
            field=models.FileField(blank=True, null=True, upload_to='permits/'),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='permit_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='permit_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='permittee',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='rep_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='species',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='tax_dec_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='tct_oct_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='total_volume_granted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='situation',
        ),
    ]
