# Generated by Django 5.1.6 on 2025-03-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_cutting_options_alter_cutting_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='situation',
            field=models.CharField(choices=[('Good', 'Good'), ('Pending', 'Pending'), ('Consumed', 'Consumed')], default='Pending', max_length=20),
        ),
    ]
